### ISSUE TITLE
Issue running the examples on linux (or maybe it is due to the latest esy version?)

### ISSUE THREAD

**Issue by JasoonS** [jchavarri/hello-ppx-esy#11]
Hi,

I'm totally inexperienced with native reason and esy, so I don't really understand what the issue is. But I was unable to get the bucklescript (`test_bs`) example working.

Here is the output when I try run `yarn build` inside the `test_bs` folder:
```
yarn run v1.22.0
$ bsb -make-world
[1/3] Building src/Index.reast
FAILED: src/Index.reast
/home/jasoons/Documents/learning/ocaml/ppx/hello-ppx-esy/test_bs/node_modules/bs-platform/lib/bsc.exe  -w -30-40+6+7+27+32..39+44+45+101 -color always -bs-jsx 2 -ppx 'esy x ppx_42'  -o src/Index.reast -bs-syntax-only -bs-binary-ast /home/jasoons/Documents/learning/ocaml/ppx/hello-ppx-esy/test_bs/src/Index.re
info building @opam/dune@opam:2.5.0@aef1678b
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/dune@opam:2.5.0
    # esy-build-package: pwd: /home/jasoons/.esy/3/b/opam__s__dune-opam__c__2.5.0-b0d2c727
    # esy-build-package: running: 'ocaml' 'bootstrap.ml' '-j' '4'
    ocamlfind -toolchain secondary ocamlc 2>.duneboot.ocamlfind-output
    ocamlfind: [WARNING] Undefined toolchain: secondary

    The ocamlfind's secondary toolchain does not seem to be correctly
    installed.
    Dune requires OCaml 4.07 or later to compile.
    Please either upgrade your compile or configure a secondary OCaml compiler
    (in opam, this can be done by installing the ocamlfind-secondary package).
    error: command failed: 'ocaml' 'bootstrap.ml' '-j' '4' (exited with 2)
    esy-build-package: exiting with errors above...

  building @opam/dune@opam:2.5.0
esy: exiting due to errors above

  We've found a bug for you!
  /home/jasoons/Documents/learning/ocaml/ppx/hello-ppx-esy/test_bs/src/Index.re

  Error while running external preprocessor
Command line: esy x ppx_42 '/tmp/camlppx81734c' '/tmp/camlppx4a215f'


FAILED: subcommand failed.
error Command failed with exit code 2.
```

And running the `esy` command inside the `test_bs` folder gave me this error:

```
info esy 0.6.2 (using esy.json)
info building @opam/dune@opam:2.5.0@aef1678b
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/dune@opam:2.5.0
    # esy-build-package: pwd: /home/jasoons/.esy/3/b/opam__s__dune-opam__c__2.5.0-b0d2c727
    # esy-build-package: running: 'ocaml' 'bootstrap.ml' '-j' '4'
    ocamlfind -toolchain secondary ocamlc 2>.duneboot.ocamlfind-output
    ocamlfind: [WARNING] Undefined toolchain: secondary

    The ocamlfind's secondary toolchain does not seem to be correctly
    installed.
    Dune requires OCaml 4.07 or later to compile.
    Please either upgrade your compile or configure a secondary OCaml compiler
    (in opam, this can be done by installing the ocamlfind-secondary package).
    error: command failed: 'ocaml' 'bootstrap.ml' '-j' '4' (exited with 2)
    esy-build-package: exiting with errors above...

  building @opam/dune@opam:2.5.0
esy: exiting due to errors above
```

Running `yarn` in the project root gives me this error:
```
yarn install v1.22.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node ./copyPlatformBinaryInPlace.js
ppx_42 does not support this platform :(

ppx_42 comes prepacked as built binaries to avoid large
dependencies at build-time.

If you want ppx_42 to support this platform natively,
please open an issue at our repository, linked above. Please
specify that you are on the linux platform,
on the x64 architecture.
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile 'bin/ppx_42-linux-x64.exe' -> 'ppx'
    at Object.copyFileSync (fs.js:1807:3)
    at copyFileSync (/home/jasoons/Documents/learning/ocaml/ppx/hello-ppx-esy/copyPlatformBinaryInPlace.js:44:8)
    at Object.<anonymous> (/home/jasoons/Documents/learning/ocaml/ppx/hello-ppx-esy/copyPlatformBinaryInPlace.js:33:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'bin/ppx_42-linux-x64.exe',
  dest: 'ppx'
}
```

This is because esy doesn't seem to create a file called `bin/ppx_42-linux-x64.exe` (or the `copyPlatformBinaryInPlace.js` file is wrong). I don't know if this could be because something changed in the latest version of esy or what.

I got the ppx working by changing the ppx-flags in the `bs-config.json` to be as follows:
```
  "ppx-flags": [
    // "esy x ppx_42"
    "../_esy/default/build/default/bin/Bin.exe"
  ],
```

Anyway, big thanks for putting this together, building ppxs isn't a very approachable task for beginners at the moment, and this definitely helps a lot!

**Comment by ng-marcus** [comment]
This seems to be Dune 2 issue. If you specify Dune 1 in the esy.json files (1.11.4 worked for me) everything should work fine.
